// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
//  // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2JAysrGth_n97q7kk-8Wwp3Gtv07N894',
    appId: '1:483410641597:web:7b6488325368788bdfedd4',
    messagingSenderId: '483410641597',
    projectId: 'magang-12f7f',
    authDomain: 'magang-12f7f.firebaseapp.com',
    storageBucket: 'magang-12f7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3d61m5r08qaFDPiyaJypLP1GW9sNmWEU',
    appId: '1:483410641597:android:2e917ebbf70c5d1fdfedd4',
    messagingSenderId: '483410641597',
    projectId: 'magang-12f7f',
    storageBucket: 'magang-12f7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgR-ZeuKpbAXJYDtVgQ5qoitPhYESxwUo',
    appId: '1:483410641597:ios:f680af5404886592dfedd4',
    messagingSenderId: '483410641597',
    projectId: 'magang-12f7f',
    storageBucket: 'magang-12f7f.appspot.com',
    iosBundleId: 'com.example.pemanasan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgR-ZeuKpbAXJYDtVgQ5qoitPhYESxwUo',
    appId: '1:483410641597:ios:f680af5404886592dfedd4',
    messagingSenderId: '483410641597',
    projectId: 'magang-12f7f',
    storageBucket: 'magang-12f7f.appspot.com',
    iosBundleId: 'com.example.pemanasan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2JAysrGth_n97q7kk-8Wwp3Gtv07N894',
    appId: '1:483410641597:web:8ff6d2d6f4f8f793dfedd4',
    messagingSenderId: '483410641597',
    projectId: 'magang-12f7f',
    authDomain: 'magang-12f7f.firebaseapp.com',
    storageBucket: 'magang-12f7f.appspot.com',
  );
}
